### ISSUE TITLE
Localization for Blazor WebAssembly not working

### ISSUE THREAD

**Issue by donquijotedelamancha** [pranavkm/LocSample#1]
This project is the clearest example I have seen on how to implement localization for Blazor WebAssembly. However after following this carefully my Blazor WebAssemly app still shows only the default version of my localized strings.
I created a [S.O. question](https://stackoverflow.com/questions/61046959/localization-in-blazor-webassembly) for this issue.
Essentially my IStringLocalizer allways show the value for the default .resx file.
I have the impression the issue can be coming from the default linker configuration for Blazor WebAssembly that strips out Internationalization information. [Link](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#configure-the-linker-for-internationalization).
However I tried adding the following on my Blazor WebAssembly project file and this didn't fix it.
`<MonoLinkerI18NAssemblies>all</MonoLinkerI18NAssemblies>`

**Comment by jaska45** [comment]
I have the same issue. The application uses neutral resources. It seems that 

```
CultureInfo.DefaultThreadCurrentCulture = culture;    
CultureInfo.DefaultThreadCurrentUICulture = culture;
```

Does not set the active culture correctly.

**Comment by jaska45** [comment]
You use 3.2.0-preview4.20178.8 instead of 3.2.0-preview3.20168.3
That might explain it. Where did you get thet. Is is not in NuGet server.

**Comment by paulstringerdb** [comment]
Having the same issue with NuGet packages "Not available in this source".
Are you obtaining them from an internal/custom package source ?

**Comment by pranavkm** [comment]
Sorry, we published the doc article a little too early. These packages are part of the Blazor preview4 release which should be released shortly.

**Comment by donquijotedelamancha** [comment]
Not a problem. Thank you for the clarification and the good work. Stay safe
